language: python

sudo: false

python:
  - 2.7
  - 3.5

install:
  - pip install -U pytest
  - pip install codecov pytest-cov
  - python setup.py install

script:
  - py.test --cov --cov-report=term-missing -vv

after_success:
  - codecov
